// <auto-generated />
namespace Gutop.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class dbinit0806 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbinit0806));
        
        string IMigrationMetadata.Id
        {
            get { return "202108060649559_dbinit0806"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
